update degrees set name = "Bachelor of Business" where degree_id = "c10026";
update degrees set name = "Bachelor of Business" where degree_id = "c10226";
update degrees set name = "Bachelor of Accounting" where degree_id = "c10235";
update degrees set name = "Bachelor of Business Administration" where degree_id = "c10340";
update degrees set name = "Bachelor of Management" where degree_id = "c10342";
update degrees set name = "Bachelor of Economics" where degree_id = "c10348";
update degrees set name = "Bachelor of Business (Honours)" where degree_id = "c09004";
update degrees set name = "Bachelor of Accounting (Honours)" where degree_id = "c09062";
update degrees set name = "Bachelor of Management (Honours)" where degree_id = "c09081";
update degrees set name = "Bachelor of Entrepreneurship (Honours)" where degree_id = "c09101";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Business" where degree_id = "c09070";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Business Diploma in Professional Engineering Practice" where degree_id = "c09071";
update degrees set name = "Bachelor of Business Bachelor of Laws (Honours)" where degree_id = "c09084";
update degrees set name = "Bachelor of Economics Bachelor of Laws (Honours)" where degree_id = "c09120";
update degrees set name = "Bachelor of Business Bachelor of Arts in International Studies" where degree_id = "c10020";
update degrees set name = "Bachelor of Business Bachelor of Laws" where degree_id = "c10125";
update degrees set name = "Bachelor of Science Bachelor of Business" where degree_id = "c10162";
update degrees set name = "Bachelor of Medical Science Bachelor of Business" where degree_id = "c10163";
update degrees set name = "Bachelor of Biotechnology Bachelor of Business" where degree_id = "c10169";
update degrees set name = "Bachelor of Business Bachelor of Science in Information Technology" where degree_id = "c10219";
update degrees set name = "Bachelor of Information Systems Bachelor of Business" where degree_id = "c10278";
update degrees set name = "Bachelor of Business Bachelor of Creative Intelligence and Innovation" where degree_id = "c10326";
update degrees set name = "Bachelor of Management Bachelor of Arts in International Studies" where degree_id = "c10343";
update degrees set name = "Bachelor of Management Bachelor of Creative Intelligence and Innovation" where degree_id = "c10355";
update degrees set name = "Bachelor of Economics Bachelor of Laws" where degree_id = "c10386";
update degrees set name = "Bachelor of Business Bachelor of Sustainability and Environment" where degree_id = "c10411";
update degrees set name = "Bachelor of Management Bachelor of Sustainability and Environment" where degree_id = "c10412";
update degrees set name = "Bachelor of Business Bachelor of Languages and Cultures" where degree_id = "c10416";
update degrees set name = "Bachelor of Management Bachelor of Languages and Cultures" where degree_id = "c10432";
update degrees set name = "Diploma in Innovation" where degree_id = "c20060";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Creative Intelligence and Innovation" where degree_id = "c09076";
update degrees set name = "Bachelor of Laws (Honours) Bachelor of Creative Intelligence and Innovation" where degree_id = "c09098";
update degrees set name = "Bachelor of Design in Fashion and Textiles Bachelor of Creative Intelligence and Innovation" where degree_id = "c10321";
update degrees set name = "Bachelor of Design in Interior Architecture Bachelor of Creative Intelligence and Innovation" where degree_id = "c10322";
update degrees set name = "Bachelor of Design in Product Design Bachelor of Creative Intelligence and Innovation" where degree_id = "c10323";
update degrees set name = "Bachelor of Design in Visual Communication Bachelor of Creative Intelligence and Innovation" where degree_id = "c10324";
update degrees set name = "Bachelor of Design in Architecture Bachelor of Creative Intelligence and Innovation" where degree_id = "c10325";
update degrees set name = "Bachelor of Science in Information Technology Bachelor of Creative Intelligence and Innovation" where degree_id = "c10327";
update degrees set name = "Bachelor of Sport and Exercise Science Bachelor of Creative Intelligence and Innovation" where degree_id = "c10328";
update degrees set name = "Bachelor of Midwifery Bachelor of Creative Intelligence and Innovation" where degree_id = "c10329";
update degrees set name = "Bachelor of Science Bachelor of Creative Intelligence and Innovation" where degree_id = "c10330";
update degrees set name = "Bachelor of Laws Bachelor of Creative Intelligence and Innovation" where degree_id = "c10338";
update degrees set name = "Bachelor of Nursing Bachelor of Creative Intelligence and Innovation" where degree_id = "c10351";
update degrees set name = "Bachelor of Advanced Science Bachelor of Creative Intelligence and Innovation" where degree_id = "c10352";
update degrees set name = "Bachelor of Biomedical Physics Bachelor of Creative Intelligence and Innovation" where degree_id = "c10353";
update degrees set name = "Bachelor of Medicinal Chemistry Bachelor of Creative Intelligence and Innovation" where degree_id = "c10354";
update degrees set name = "Bachelor of Design in Animation Bachelor of Creative Intelligence and Innovation" where degree_id = "c10356";
update degrees set name = "Bachelor of Communication (Digital and Social Media) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10359";
update degrees set name = "Bachelor of Communication (Media Arts and Production) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10373";
update degrees set name = "Bachelor of Communication (Public Communication) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10374";
update degrees set name = "Bachelor of Communication (Social and Political Sciences) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10375";
update degrees set name = "Bachelor of Communication (Journalism) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10376";
update degrees set name = "Bachelor of Communication (Creative Writing) Bachelor of Creative Intelligence and Innovation" where degree_id = "c10377";
update degrees set name = "Bachelor of Forensic Science Bachelor of Creative Intelligence and Innovation" where degree_id = "c10389";
update degrees set name = "Bachelor of Landscape Architecture (Honours)" where degree_id = "c09079";
update degrees set name = "Bachelor of Design in Architecture" where degree_id = "c10004";
update degrees set name = "Bachelor of Construction Project Management" where degree_id = "c10214";
update degrees set name = "Bachelor of Design in Interior Architecture" where degree_id = "c10271";
update degrees set name = "Bachelor of Design in Animation" where degree_id = "c10273";
update degrees set name = "Bachelor of Design in Product Design" where degree_id = "c10304";
update degrees set name = "Bachelor of Design in Fashion and Textiles" where degree_id = "c10306";
update degrees set name = "Bachelor of Design in Visual Communication" where degree_id = "c10308";
update degrees set name = "Bachelor of Property Economics" where degree_id = "c10310";
update degrees set name = "Bachelor of Design (Honours) in Architecture" where degree_id = "c09048";
update degrees set name = "Bachelor of Design (Honours) in Photography" where degree_id = "c09052";
update degrees set name = "Bachelor of Design (Honours) in Interior Architecture" where degree_id = "c09055";
update degrees set name = "Bachelor of Design (Honours) in Animation" where degree_id = "c09056";
update degrees set name = "Bachelor of Design (Honours) in Product Design" where degree_id = "c09059";
update degrees set name = "Bachelor of Design (Honours) in Fashion and Textiles" where degree_id = "c09060";
update degrees set name = "Bachelor of Design (Honours) in Visual Communication" where degree_id = "c09061";
update degrees set name = "Bachelor of Property Economics (Honours)" where degree_id = "c09063";
update degrees set name = "Bachelor of Construction Project Management Bachelor of Arts in International Studies" where degree_id = "c10215";
update degrees set name = "Bachelor of Design in Interior Architecture Bachelor of Arts in International Studies" where degree_id = "c10272";
update degrees set name = "Bachelor of Design in Animation Bachelor of Arts in International Studies" where degree_id = "c10274";
update degrees set name = "Bachelor of Design in Product Design Bachelor of Arts in International Studies" where degree_id = "c10305";
update degrees set name = "Bachelor of Design in Fashion and Textiles Bachelor of Arts in International Studies" where degree_id = "c10307";
update degrees set name = "Bachelor of Design in Visual Communication Bachelor of Arts in International Studies" where degree_id = "c10309";
update degrees set name = "Bachelor of Property Economics Bachelor of Arts in International Studies" where degree_id = "c10320";
update degrees set name = "Bachelor of Design in Architecture Master of Architecture" where degree_id = "c10413";
update degrees set name = "Bachelor of Construction Project Management Bachelor of Languages and Cultures" where degree_id = "c10420";
update degrees set name = "Bachelor of Design in Interior Architecture Bachelor of Languages and Cultures" where degree_id = "c10423";
update degrees set name = "Bachelor of Design in Animation Bachelor of Languages and Cultures" where degree_id = "c10424";
update degrees set name = "Bachelor of Design in Product Design Bachelor of Languages and Cultures" where degree_id = "c10428";
update degrees set name = "Bachelor of Design in Fashion and Textiles Bachelor of Languages and Cultures" where degree_id = "c10429";
update degrees set name = "Bachelor of Design in Visual Communication Bachelor of Languages and Cultures" where degree_id = "c10430";
update degrees set name = "Bachelor of Property Economics Bachelor of Languages and Cultures" where degree_id = "c10431";
update degrees set name = "Bachelor of Arts in Educational Studies" where degree_id = "c10209";
update degrees set name = "Bachelor of Arts in Educational Studies Bachelor of Arts in International Studies" where degree_id = "c10392";
update degrees set name = "Bachelor of Science Master of Teaching in Secondary Education" where degree_id = "c10404";
update degrees set name = "Bachelor of Communication (Creative Writing) Master of Teaching in Secondary Education" where degree_id = "c10405";
update degrees set name = "Bachelor of Engineering Studies Master of Teaching in Secondary Education" where degree_id = "c10406";
update degrees set name = "Bachelor of Arts in Educational Studies Bachelor of Languages and Cultures" where degree_id = "c10443";
update degrees set name = "Bachelor of Education Bachelor of Languages and Cultures" where degree_id = "c10444";
update degrees set name = "Bachelor of Engineering (Honours)" where degree_id = "c09066";
update degrees set name = "Bachelor of Engineering (Honours) Diploma in Professional Engineering Practice" where degree_id = "c09067";
update degrees set name = "Bachelor of Engineering Science" where degree_id = "c10066";
update degrees set name = "Bachelor of Engineering Studies" where degree_id = "c10408";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Science" where degree_id = "c09072";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Science Diploma in Professional Engineering Practice" where degree_id = "c09073";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Medical Science" where degree_id = "c09074";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Medical Science Diploma in Professional Engineering Practice" where degree_id = "c09075";
update degrees set name = "Bachelor of Engineering Science Bachelor of Laws (Honours)" where degree_id = "c09087";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Arts in International Studies" where degree_id = "c09123";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Arts in International Studies Diploma in Professional Engineering Practice" where degree_id = "c09124";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Languages and Cultures" where degree_id = "c09127";
update degrees set name = "Bachelor of Engineering (Honours) Bachelor of Languages and Cultures Diploma in Professional Engineering Practice" where degree_id = "c09128";
update degrees set name = "Bachelor of Engineering Science Bachelor of Laws" where degree_id = "c10136";
update degrees set name = "Bachelor of Computing Science (Honours)" where degree_id = "c09119";
update degrees set name = "Bachelor of Information Technology" where degree_id = "c10143";
update degrees set name = "Bachelor of Science in Information Technology" where degree_id = "c10148";
update degrees set name = "Bachelor of Science in Games Development" where degree_id = "c10229";
update degrees set name = "Bachelor of Science in Information Technology Diploma in Information Technology Professional Practice" where degree_id = "c10345";
update degrees set name = "Bachelor of Information Systems" where degree_id = "c10395";
update degrees set name = "Diploma in Information Technology Professional Practice" where degree_id = "c20056";
update degrees set name = "Bachelor of Science (Honours) in Information Technology" where degree_id = "c09019";
update degrees set name = "Bachelor of Science in Information Technology Bachelor of Laws (Honours)" where degree_id = "c09088";
update degrees set name = "Bachelor of Science in Information Technology Bachelor of Arts in International Studies" where degree_id = "c10239";
update degrees set name = "Bachelor of Science in Information Technology Bachelor of Laws" where degree_id = "c10245";
update degrees set name = "Bachelor of Science in Information Technology Bachelor of Languages and Cultures" where degree_id = "c10421";
update degrees set name = "Bachelor of Laws (Honours)" where degree_id = "c09083";
update degrees set name = "Bachelor of Laws" where degree_id = "c10124";
update degrees set name = "Bachelor of Science Bachelor of Laws (Honours)" where degree_id = "c09085";
update degrees set name = "Bachelor of Medical Science Bachelor of Laws (Honours)" where degree_id = "c09086";
update degrees set name = "Bachelor of Communication (Creative Writing) Bachelor of Laws (Honours)" where degree_id = "c09089";
update degrees set name = "Bachelor of Communication (Digital and Social Media) Bachelor of Laws (Honours)" where degree_id = "c09091";
update degrees set name = "Bachelor of Communication (Journalism) Bachelor of Laws (Honours)" where degree_id = "c09093";
update degrees set name = "Bachelor of Communication (Media Arts and Production) Bachelor of Laws (Honours)" where degree_id = "c09094";
update degrees set name = "Bachelor of Communication (Public Communication) Bachelor of Laws (Honours)" where degree_id = "c09095";
update degrees set name = "Bachelor of Communication (Social and Political Sciences) Bachelor of Laws (Honours)" where degree_id = "c09096";
update degrees set name = "Bachelor of Laws (Honours) Bachelor of Arts in International Studies" where degree_id = "c09097";
update degrees set name = "Bachelor of Forensic Science Bachelor of Laws (Honours)" where degree_id = "c09121";
update degrees set name = "Bachelor of Laws (Honours) Bachelor of Languages and Cultures" where degree_id = "c09126";
update degrees set name = "Bachelor of Science Bachelor of Laws" where degree_id = "c10126";
update degrees set name = "Bachelor of Laws Bachelor of Arts in International Studies" where degree_id = "c10129";
update degrees set name = "Bachelor of Medical Science Bachelor of Laws" where degree_id = "c10131";
update degrees set name = "Bachelor of Communication (Creative Writing) Bachelor of Laws" where degree_id = "c10378";
update degrees set name = "Bachelor of Communication (Digital and Social Media) Bachelor of Laws" where degree_id = "c10379";
update degrees set name = "Bachelor of Communication (Journalism) Bachelor of Laws" where degree_id = "c10380";
update degrees set name = "Bachelor of Communication (Media Arts and Production) Bachelor of Laws" where degree_id = "c10381";
update degrees set name = "Bachelor of Communication (Public Communication) Bachelor of Laws" where degree_id = "c10382";
update degrees set name = "Bachelor of Communication (Social and Political Sciences) Bachelor of Laws" where degree_id = "c10383";
update degrees set name = "Bachelor of Forensic Science Bachelor of Laws" where degree_id = "c10391";
update degrees set name = "Bachelor of Laws Bachelor of Languages and Cultures" where degree_id = "c10418";
update degrees set name = "Bachelor of Biomedical Science" where degree_id = "c10115";
update degrees set name = "Bachelor of Biotechnology" where degree_id = "c10172";
update degrees set name = "Bachelor of Medical Science" where degree_id = "c10184";
update degrees set name = "Bachelor of Environmental Biology" where degree_id = "c10223";
update degrees set name = "Bachelor of Marine Biology" where degree_id = "c10228";
update degrees set name = "Bachelor of Science" where degree_id = "c10242";
update degrees set name = "Bachelor of Medicinal Chemistry" where degree_id = "c10275";
update degrees set name = "Bachelor of Biomedical Physics" where degree_id = "c10346";
update degrees set name = "Bachelor of Advanced Science" where degree_id = "c10347";
update degrees set name = "Bachelor of Science in Analytics" where degree_id = "c10384";
update degrees set name = "Bachelor of Forensic Science" where degree_id = "c10387";
update degrees set name = "Bachelor of Science (Honours) in Mathematics" where degree_id = "c09020";
update degrees set name = "Bachelor of Biotechnology (Honours)" where degree_id = "c09022";
update degrees set name = "Bachelor of Science (Honours) in Biomedical Science" where degree_id = "c09023";
update degrees set name = "Bachelor of Science (Honours) in Applied Chemistry" where degree_id = "c09026";
update degrees set name = "Bachelor of Science (Honours) in Environmental Science" where degree_id = "c09029";
update degrees set name = "Bachelor of Medical Science (Honours)" where degree_id = "c09031";
update degrees set name = "Bachelor of Science (Honours) in Applied Physics" where degree_id = "c09035";
update degrees set name = "Bachelor of Science (Honours) in Nanotechnology" where degree_id = "c09046";
update degrees set name = "Bachelor of Medicinal Chemistry (Honours)" where degree_id = "c09077";
update degrees set name = "Bachelor of Biomedical Physics (Honours)" where degree_id = "c09078";
update degrees set name = "Bachelor of Science (Honours) in Analytics" where degree_id = "c09099";
update degrees set name = "Bachelor of Forensic Science (Honours)" where degree_id = "c09100";
update degrees set name = "Bachelor of Medical Science Bachelor of Arts in International Studies" where degree_id = "c10167";
update degrees set name = "Bachelor of Science Bachelor of Arts in International Studies" where degree_id = "c10243";
update degrees set name = "Bachelor of Science in Analytics Bachelor of Arts in International Studies" where degree_id = "c10385";
update degrees set name = "Bachelor of Forensic Science Bachelor of Arts in International Studies" where degree_id = "c10388";
update degrees set name = "Bachelor of Science Bachelor of Sustainability and Environment" where degree_id = "c10399";
update degrees set name = "Bachelor of Medical Science Bachelor of Languages and Cultures" where degree_id = "c10419";
update degrees set name = "Bachelor of Science Bachelor of Languages and Cultures" where degree_id = "c10422";
update degrees set name = "Bachelor of Science in Analytics Bachelor of Languages and Cultures" where degree_id = "c10440";
update degrees set name = "Bachelor of Forensic Science Bachelor of Languages and Cultures" where degree_id = "c10442";
update degrees set name = "Bachelor of Creative Intelligence and Innovation (Honours)" where degree_id = "c09122";
