insert into majors (major_code, name, type, degree_id) values ("MAJ08981", "Advertising and Marketing Communications", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ10086", "Business Analytics in Marketing", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08215", "Financial Services", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08219", "Sustainable Enterprise", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ09402", "Extended Economics", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08060", "Extended Finance", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08046", "Extended Management", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08063", "Extended Marketing", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08981", "Advertising and Marketing Communications", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ10086", "Business Analytics in Marketing", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08215", "Financial Services", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08219", "Sustainable Enterprise", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ09402", "Extended Economics", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08060", "Extended Finance", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08046", "Extended Management", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08063", "Extended Marketing", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08981", "Advertising and Marketing Communications", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ10086", "Business Analytics in Marketing", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08215", "Financial Services", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("SMJ08219", "Sustainable Enterprise", "sub-major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ09402", "Extended Economics", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08060", "Extended Finance", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08046", "Extended Management", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("MAJ08063", "Extended Marketing", "major", "c10026");
insert into majors (major_code, name, type, degree_id) values ("STM90850", "Core subjects (Business)", "sub-major", "c10226");
insert into majors (major_code, name, type, degree_id) values ("STM90850", "Core subjects (Business)", "sub-major", "c10226");
insert into majors (major_code, name, type, degree_id) values ("STM90850", "Core subjects (Business)", "sub-major", "c10226");
insert into majors (major_code, name, type, degree_id) values ("MAJ08437", "Accounting", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09401", "Business Law", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09209", "Economics", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08440", "Finance", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08446", "Human Resource Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ02041", "Information Technology", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08442", "International Business", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08438", "Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08441", "Marketing", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08131", "Advanced Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08137", "Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02036", "Business Information Systems", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08120", "Business Innovation and Financial Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09030", "Business Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09058", "Econometrics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09028", "Economics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08203", "Event Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08123", "Finance", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08116", "Financial Reporting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08128", "Human Resource Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08139", "International Business Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08129", "International Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09034", "International Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02037", "Information Technology", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09035", "Language other than English", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08130", "Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08109", "Management Consulting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08195", "Accounting in Practice", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08138", "Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01007", "Mathematics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01025", "Quantitative Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09036", "Specialist Country Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08126", "Sport Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01009", "Statistics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08204", "Strategic Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09033", "Taxation Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08127", "Tourism Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("STM90285", "Core subjects (Accounting)", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08443", "Tourism Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08445", "Sport Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08437", "Accounting", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09401", "Business Law", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09209", "Economics", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08440", "Finance", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08446", "Human Resource Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ02041", "Information Technology", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08442", "International Business", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08438", "Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08441", "Marketing", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08131", "Advanced Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08137", "Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02036", "Business Information Systems", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08120", "Business Innovation and Financial Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09030", "Business Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09058", "Econometrics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09028", "Economics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08203", "Event Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08123", "Finance", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08116", "Financial Reporting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08128", "Human Resource Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08139", "International Business Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08129", "International Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09034", "International Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02037", "Information Technology", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09035", "Language other than English", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08130", "Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08109", "Management Consulting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08195", "Accounting in Practice", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08138", "Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01007", "Mathematics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01025", "Quantitative Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09036", "Specialist Country Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08126", "Sport Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01009", "Statistics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08204", "Strategic Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09033", "Taxation Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08127", "Tourism Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("STM90285", "Core subjects (Accounting)", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08443", "Tourism Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08445", "Sport Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08437", "Accounting", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09401", "Business Law", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ09209", "Economics", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08440", "Finance", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08446", "Human Resource Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ02041", "Information Technology", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08442", "International Business", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08438", "Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08441", "Marketing", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08131", "Advanced Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08137", "Advertising", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02036", "Business Information Systems", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08120", "Business Innovation and Financial Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09030", "Business Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09058", "Econometrics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09028", "Economics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08203", "Event Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08123", "Finance", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08116", "Financial Reporting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08128", "Human Resource Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08139", "International Business Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08129", "International Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09034", "International Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ02037", "Information Technology", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09035", "Language other than English", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08130", "Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08109", "Management Consulting", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08195", "Accounting in Practice", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08138", "Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01007", "Mathematics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01025", "Quantitative Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09036", "Specialist Country Studies", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08126", "Sport Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ01009", "Statistics", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08204", "Strategic Marketing", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ09033", "Taxation Law", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("SMJ08127", "Tourism Management", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("STM90285", "Core subjects (Accounting)", "sub-major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08443", "Tourism Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("MAJ08445", "Sport Management", "major", "c10235");
insert into majors (major_code, name, type, degree_id) values ("STM90273", "Core subjects (Business)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM91052", "Law stream (Honours)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM90273", "Core subjects (Business)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM91052", "Law stream (Honours)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM90273", "Core subjects (Business)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM91052", "Law stream (Honours)", "sub-major", "c09084");
insert into majors (major_code, name, type, degree_id) values ("STM91176", "Creative Intelligence", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM91177", "Innovation and Entrepreneurship", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM91176", "Creative Intelligence", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM91177", "Innovation and Entrepreneurship", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM91176", "Creative Intelligence", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM91177", "Innovation and Entrepreneurship", "sub-major", "c20060");
insert into majors (major_code, name, type, degree_id) values ("STM90839", "Core subjects (Creative Intelligence and Innovation)", "sub-major", "c09098");
insert into majors (major_code, name, type, degree_id) values ("STM90839", "Core subjects (Creative Intelligence and Innovation)", "sub-major", "c09098");
insert into majors (major_code, name, type, degree_id) values ("STM90839", "Core subjects (Creative Intelligence and Innovation)", "sub-major", "c09098");
insert into majors (major_code, name, type, degree_id) values ("STM91202", "Core subjects (Landscape UG)", "sub-major", "c09079");
insert into majors (major_code, name, type, degree_id) values ("STM91202", "Core subjects (Landscape UG)", "sub-major", "c09079");
insert into majors (major_code, name, type, degree_id) values ("STM91202", "Core subjects (Landscape UG)", "sub-major", "c09079");
insert into majors (major_code, name, type, degree_id) values ("STM91342", "Core subjects (Architecture)", "sub-major", "c10004");
insert into majors (major_code, name, type, degree_id) values ("STM91342", "Core subjects (Architecture)", "sub-major", "c10004");
insert into majors (major_code, name, type, degree_id) values ("STM91342", "Core subjects (Architecture)", "sub-major", "c10004");
insert into majors (major_code, name, type, degree_id) values ("STM90373", "Core subjects (Construction)", "sub-major", "c10214");
insert into majors (major_code, name, type, degree_id) values ("STM90373", "Core subjects (Construction)", "sub-major", "c10214");
insert into majors (major_code, name, type, degree_id) values ("STM90373", "Core subjects (Construction)", "sub-major", "c10214");
insert into majors (major_code, name, type, degree_id) values ("STM91579", "Secondary Education core", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91492", "Core (Physical Sciences - Mathematics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91490", "Core (Physical Sciences - Chemistry and Physics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91579", "Secondary Education core", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91492", "Core (Physical Sciences - Mathematics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91490", "Core (Physical Sciences - Chemistry and Physics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91579", "Secondary Education core", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91492", "Core (Physical Sciences - Mathematics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM91490", "Core (Physical Sciences - Chemistry and Physics)", "sub-major", "c10404");
insert into majors (major_code, name, type, degree_id) values ("STM90994", "Professional Engineering Practice stream", "sub-major", "c09066");
insert into majors (major_code, name, type, degree_id) values ("STM90994", "Professional Engineering Practice stream", "sub-major", "c09066");
insert into majors (major_code, name, type, degree_id) values ("STM90994", "Professional Engineering Practice stream", "sub-major", "c09066");
insert into majors (major_code, name, type, degree_id) values ("STM90106", "Core subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90848", "Civil and Environmental Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90849", "Mechanical and Mechatronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM91414", "Electrical and Electronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03472", "Biomedical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03001", "Civil Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03002", "Civil and Environmental Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03518", "Data Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03005", "Electrical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03524", "Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03007", "Mechanical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03012", "Mechanical and Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03504", "Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03523", "Software Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03537", "Electrical and Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03540", "Flexible Engineering BE (Hons)", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90993", "Professional Engineering Practice Program subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90106", "Core subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90848", "Civil and Environmental Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90849", "Mechanical and Mechatronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM91414", "Electrical and Electronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03472", "Biomedical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03001", "Civil Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03002", "Civil and Environmental Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03518", "Data Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03005", "Electrical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03524", "Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03007", "Mechanical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03012", "Mechanical and Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03504", "Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03523", "Software Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03537", "Electrical and Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03540", "Flexible Engineering BE (Hons)", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90993", "Professional Engineering Practice Program subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90106", "Core subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90848", "Civil and Environmental Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90849", "Mechanical and Mechatronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM91414", "Electrical and Electronic Engineering specialist stream", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03472", "Biomedical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03001", "Civil Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03002", "Civil and Environmental Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03518", "Data Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03005", "Electrical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03524", "Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03007", "Mechanical Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03012", "Mechanical and Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03504", "Mechatronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03523", "Software Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03537", "Electrical and Electronic Engineering", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("MAJ03540", "Flexible Engineering BE (Hons)", "major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("STM90993", "Professional Engineering Practice Program subjects", "sub-major", "c09067");
insert into majors (major_code, name, type, degree_id) values ("SMJ10089", "Internet of Things (Systems and Devices)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("SMJ10090", "Internet of Things (Software)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("STM90356", "Core subjects", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03134", "Civil Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03515", "Data Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03413", "Electrical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03527", "Electronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03139", "Mechanical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03507", "Mechatronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03520", "Software Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03542", "Flexible Engineering BEngSc", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("SMJ10089", "Internet of Things (Systems and Devices)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("SMJ10090", "Internet of Things (Software)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("STM90356", "Core subjects", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03134", "Civil Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03515", "Data Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03413", "Electrical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03527", "Electronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03139", "Mechanical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03507", "Mechatronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03520", "Software Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03542", "Flexible Engineering BEngSc", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("SMJ10089", "Internet of Things (Systems and Devices)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("SMJ10090", "Internet of Things (Software)", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("STM90356", "Core subjects", "sub-major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03134", "Civil Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03515", "Data Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03413", "Electrical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03527", "Electronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03139", "Mechanical Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03507", "Mechatronic Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03520", "Software Engineering", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("MAJ03542", "Flexible Engineering BEngSc", "major", "c10066");
insert into majors (major_code, name, type, degree_id) values ("STM91173", "Core subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91172", "Core Honours subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ10053", "Artificial Intelligence and Data Analytics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02080", "Business Information Systems Management", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02900", "Cybersecurity and Privacy", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03519", "Enterprise Systems Development", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02092", "Interaction Design", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01156", "Mathematical Analysis", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03445", "Networking and Cybersecurity", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01157", "Operations Research", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02901", "Quantum Information Science", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01158", "Statistics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91173", "Core subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91172", "Core Honours subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ10053", "Artificial Intelligence and Data Analytics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02080", "Business Information Systems Management", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02900", "Cybersecurity and Privacy", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03519", "Enterprise Systems Development", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02092", "Interaction Design", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01156", "Mathematical Analysis", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03445", "Networking and Cybersecurity", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01157", "Operations Research", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02901", "Quantum Information Science", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01158", "Statistics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91173", "Core subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91172", "Core Honours subjects (Computing Science)", "sub-major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ10053", "Artificial Intelligence and Data Analytics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02080", "Business Information Systems Management", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02900", "Cybersecurity and Privacy", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03519", "Enterprise Systems Development", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02092", "Interaction Design", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01156", "Mathematical Analysis", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ03445", "Networking and Cybersecurity", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01157", "Operations Research", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ02901", "Quantum Information Science", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("MAJ01158", "Statistics", "major", "c09119");
insert into majors (major_code, name, type, degree_id) values ("STM91312", "Software Development Studios", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM91313", "Work Integrated Learning", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM91312", "Software Development Studios", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM91313", "Work Integrated Learning", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM91312", "Software Development Studios", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM91313", "Work Integrated Learning", "sub-major", "c10143");
insert into majors (major_code, name, type, degree_id) values ("STM90651", "Core subjects (Information Technology)", "sub-major", "c10148");
insert into majors (major_code, name, type, degree_id) values ("STM90651", "Core subjects (Information Technology)", "sub-major", "c10148");
insert into majors (major_code, name, type, degree_id) values ("STM90651", "Core subjects (Information Technology)", "sub-major", "c10148");
insert into majors (major_code, name, type, degree_id) values ("STM90832", "Core (Law)", "sub-major", "c10124");
insert into majors (major_code, name, type, degree_id) values ("STM90832", "Core (Law)", "sub-major", "c10124");
insert into majors (major_code, name, type, degree_id) values ("STM90832", "Core (Law)", "sub-major", "c10124");
insert into majors (major_code, name, type, degree_id) values ("STM91191", "Core subjects (Biotechnology)", "sub-major", "c10172");
insert into majors (major_code, name, type, degree_id) values ("STM91191", "Core subjects (Biotechnology)", "sub-major", "c10172");
insert into majors (major_code, name, type, degree_id) values ("STM91191", "Core subjects (Biotechnology)", "sub-major", "c10172");
insert into majors (major_code, name, type, degree_id) values ("STM90680", "Foundation stream (Life Sciences)", "sub-major", "c10184");
insert into majors (major_code, name, type, degree_id) values ("STM90680", "Foundation stream (Life Sciences)", "sub-major", "c10184");
insert into majors (major_code, name, type, degree_id) values ("STM90680", "Foundation stream (Life Sciences)", "sub-major", "c10184");
