insert into ug_degrees (degree_id, courseAreaName) values ("c10026", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10226", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10226", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10235", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10235", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10340", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10340", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10342", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10342", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10348", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10348", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09004", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09062", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09062", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09081", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09081", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09101", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09101", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09070", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09071", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09071", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09084", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09084", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09120", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c09120", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10020", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10020", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10125", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10125", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10162", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10162", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10163", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10163", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10169", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10169", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10219", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10219", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10278", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10278", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10326", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10326", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10343", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10343", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10355", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10355", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10386", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10386", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10411", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10411", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10412", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10412", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10416", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10416", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10432", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c10432", "Business");
insert into ug_degrees (degree_id, courseAreaName) values ("c20060", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c09076", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c09098", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c09098", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10321", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10321", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10322", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10322", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10323", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10323", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10324", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10324", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10325", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10325", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10326", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10326", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10327", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10327", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10328", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10328", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10329", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10329", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10330", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10330", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10338", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10338", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10351", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10351", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10352", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10352", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10353", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10353", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10354", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10354", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10355", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10355", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10356", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10356", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10359", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10359", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10373", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10373", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10374", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10374", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10375", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10375", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10376", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10376", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10377", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10377", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10389", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c10389", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c20060", "Creative Intelligence and Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c09079", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10004", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10004", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10214", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10214", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10271", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10271", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10273", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10273", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10304", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10304", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10306", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10306", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10308", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10308", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10310", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10310", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09048", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09052", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09052", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09055", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09055", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09056", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09056", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09059", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09059", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09060", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09060", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09061", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09061", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09063", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c09063", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10215", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10272", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10272", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10274", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10274", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10305", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10305", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10307", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10307", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10309", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10309", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10320", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10320", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10321", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10321", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10322", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10322", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10323", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10323", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10324", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10324", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10325", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10325", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10356", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10356", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10413", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10413", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10420", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10420", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10423", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10423", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10424", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10424", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10428", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10428", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10429", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10429", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10430", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10430", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10431", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10431", "Design, Architecture and Building");
insert into ug_degrees (degree_id, courseAreaName) values ("c10209", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10392", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10404", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10404", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10405", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10405", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10406", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10406", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10443", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10443", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10444", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c10444", "Education");
insert into ug_degrees (degree_id, courseAreaName) values ("c09066", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09067", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09067", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10066", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10066", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10408", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10408", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09070", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09071", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09071", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09072", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09072", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09073", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09073", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09074", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09074", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09075", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09075", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09076", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09076", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09087", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09087", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09123", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09123", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09124", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09124", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09127", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09127", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09128", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09128", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10136", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10136", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10406", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c10406", "Engineering");
insert into ug_degrees (degree_id, courseAreaName) values ("c09119", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10143", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10143", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10148", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10148", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10229", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10229", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10345", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10345", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10395", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10395", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c20056", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c20056", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c09019", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c09088", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10219", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10219", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10239", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10239", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10245", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10245", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10278", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10278", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10327", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10327", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10421", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c10421", "Information Technology");
insert into ug_degrees (degree_id, courseAreaName) values ("c09083", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10124", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10124", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09084", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09085", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09085", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09086", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09086", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09087", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09087", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09088", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09088", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09089", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09089", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09091", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09091", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09093", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09093", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09094", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09094", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09095", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09095", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09096", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09096", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09097", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09097", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09098", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09098", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09120", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09120", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09121", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09121", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09126", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c09126", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10125", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10125", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10126", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10126", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10129", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10129", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10131", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10131", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10136", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10136", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10245", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10245", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10338", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10338", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10378", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10378", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10379", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10379", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10380", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10380", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10381", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10381", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10382", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10382", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10383", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10383", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10386", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10386", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10391", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10391", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10418", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10418", "Law");
insert into ug_degrees (degree_id, courseAreaName) values ("c10115", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10172", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10172", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10184", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10184", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10223", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10223", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10228", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10228", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10242", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10242", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10275", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10275", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10346", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10346", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10347", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10347", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10384", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10384", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10387", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10387", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09020", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09022", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09022", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09023", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09023", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09026", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09026", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09029", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09029", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09031", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09031", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09035", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09035", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09046", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09046", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09077", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09077", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09078", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09078", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09099", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09099", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09100", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09100", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09072", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09073", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09073", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09074", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09074", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09075", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09075", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09085", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09085", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09086", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09086", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09121", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c09121", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10126", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10126", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10131", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10131", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10162", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10162", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10163", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10163", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10167", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10167", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10169", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10169", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10243", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10243", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10330", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10330", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10352", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10352", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10353", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10353", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10354", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10354", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10385", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10385", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10388", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10388", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10389", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10389", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10391", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10391", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10399", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10399", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10404", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10404", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10419", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10419", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10422", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10422", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10440", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10440", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10442", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c10442", "Science");
insert into ug_degrees (degree_id, courseAreaName) values ("c20060", "Transdisciplinary Innovation");
insert into ug_degrees (degree_id, courseAreaName) values ("c09122", "Transdisciplinary Innovation");
