service: course-recommendation-backend
frameworkVersion: '2'
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${env:PROFILE_NAME}
  stage: dev
  region: ap-southeast-2
  vpc:
    securityGroupIds:
      - sg-38840175
    subnetIds:
      - subnet-d3d5129b
      - subnet-1d42887b
      - subnet-870c48df
  environment:
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    HOST: ${env:HOST}

package:
 exclude:
   - lambda/local/
   - rds/
   - scripts/

functions:
  createStudent:
    handler: lambda/createStudent.handler
    events:
      - http:
          path: student
          method: POST
          cors: true
